// This file is automatically generated by scripts/gen-projects.js

export const TOOLS = [
  "Android",
  "Angular",
  "AngularJs",
  "Bulma",
  "C++",
  "Chrome",
  "Clang",
  "Contentful",
  "File-based routing",
  "Firefox",
  "Flutter",
  "Google Cloud Run",
  "GraphQL",
  "Graphics",
  "Hacker News API",
  "Hexo",
  "IOS",
  "ImageMagick",
  "Instagram API",
  "JavaScript",
  "Javascript",
  "Make",
  "Messenger",
  "NextJs",
  "NodeJs",
  "OpenGL",
  "PDF",
  "PDFkit",
  "PDFs",
  "Plain JavaScript",
  "Puppeteer",
  "Python",
  "React",
  "SSR",
  "SVG",
  "Shell",
  "Static Site",
  "Svelte",
  "Tailwind",
  "Three-Js",
  "Typescript",
  "Vue",
  "VueJs",
  "Web Scraping",
  "Wordpress",
  "fuse.js",
  "hammer.js",
  "hotkeys.js",
  "nuxt",
  "pts.js",
  "tailwind",
  "tailwind.css"
] as const;

export const ICONS = [
  "android",
  "angular",
  "apple",
  "chrome",
  "contentful",
  "cpp",
  "docker",
  "firefox",
  "flutter",
  "hackernews",
  "instagram",
  "javascript",
  "messenger",
  "next",
  "opengl",
  "pdf",
  "pen",
  "puppeteer",
  "python",
  "react",
  "svelte",
  "tailwind",
  "three",
  "typescript",
  "vue",
  "wordpress"
] as const;

export const TAGS = [
  "3d",
  "airbnb",
  "chatbot",
  "cli",
  "cloud",
  "demo",
  "extension",
  "fun",
  "game",
  "hn",
  "library",
  "mobile app",
  "pdf",
  "productivity",
  "tool",
  "web app",
  "web site"
] as const;

export const PROJECTS = [
  {
    "slug": "open_gl_terrain_demo",
    "name": "Open GL - Terrain Demo",
    "year": 2024,
    "tags": [
      "3d",
      "fun",
      "demo"
    ],
    "description": "A 3D demo of an open world with procedural terrain",
    "code_link": "https://github.com/benwinding/open-gl-terrain-example",
    "tools": [
      "C++",
      "OpenGL",
      "Clang",
      "Make"
    ],
    "icons": [
      "cpp",
      "opengl"
    ],
    "thumbnail": "/imgur/projects/_resized/87gbachjk.jpg"
  },
  {
    "slug": "everything's_normal",
    "name": "Everything's Normal",
    "year": 2022,
    "tags": [
      "web site",
      "3d",
      "fun"
    ],
    "description": "Visualize a rotating normal map",
    "deploy_link": "https://benwinding.com/everythings-normal/",
    "tools": [
      "Javascript",
      "Three-Js"
    ],
    "icons": [
      "three",
      "javascript"
    ],
    "thumbnail": "/imgur/projects/_resized/kbwda787dwa.jpg"
  },
  {
    "slug": "saltbush_farm",
    "name": "Saltbush Farm",
    "year": 2022,
    "tags": [
      "web site",
      "airbnb"
    ],
    "description": "Luxury farmhouse accomodation",
    "deploy_link": "https://saltbush.farm",
    "tools": [
      "Typescript",
      "NextJs",
      "NodeJs",
      "Tailwind"
    ],
    "icons": [
      "next",
      "typescript",
      "tailwind"
    ],
    "thumbnail": "/imgur/projects/_resized/i8hdawubiad.jpg"
  },
  {
    "slug": "surprise_bread",
    "name": "Surprise Bread",
    "year": 2022,
    "tags": [
      "web site",
      "fun"
    ],
    "description": "Delicious handmade sourdough bread, delivered to your door!",
    "deploy_link": "https://surprisebread.com.au",
    "tools": [
      "Javascript",
      "React",
      "NextJs",
      "Tailwind"
    ],
    "icons": [
      "react",
      "javascript"
    ],
    "thumbnail": "/imgur/projects/_resized/98yadubwdw.jpg"
  },
  {
    "slug": "trickhub",
    "name": "Trickhub",
    "year": 2022,
    "tags": [
      "web site",
      "fun"
    ],
    "description": "Share and view tricks from extreme sports",
    "deploy_link": "https://trickhub.co",
    "tools": [
      "Typescript",
      "NextJs",
      "NodeJs"
    ],
    "icons": [
      "next",
      "typescript"
    ],
    "wip": true,
    "thumbnail": "/imgur/projects/_resized/u7gdawdbu8766.jpg"
  },
  {
    "slug": "3d_laptop",
    "name": "3D Laptop",
    "year": 2021,
    "tags": [
      "fun",
      "3d",
      "web app"
    ],
    "description": "A 3D version of this website!",
    "code_link": "https://github.com/benwinding/benw-portal/blob/master/static/3d/",
    "deploy_link": "https://benwinding.com/3d",
    "tools": [
      "React",
      "Three-Js"
    ],
    "icons": [
      "react",
      "three"
    ],
    "open_same_page": true,
    "thumbnail": "/imgur/projects/_resized/hdiuawd78awd.jpg"
  },
  {
    "slug": "bender",
    "name": "Bender",
    "year": 2021,
    "tags": [
      "fun",
      "web app"
    ],
    "description": "A dating app to meet cool guys like me, inspired by Tinder!",
    "code_link": "https://github.com/benwinding/benw-portal/blob/master/static/bender.html",
    "deploy_link": "http://benwinding.com/bender.html",
    "tools": [
      "Plain JavaScript",
      "hammer.js",
      "tailwind.css"
    ],
    "icons": [
      "javascript",
      "tailwind"
    ],
    "thumbnail": "/imgur/projects/_resized/aaijwdak12361.jpg"
  },
  {
    "slug": "eat_the_donut",
    "name": "Eat The Donut",
    "year": 2021,
    "tags": [
      "fun",
      "3d",
      "web app",
      "game"
    ],
    "description": "A 3D game where you eat a donut!",
    "code_link": "https://github.com/benwinding/benw-portal/blob/master/static/eat-the-donut.html",
    "deploy_link": "https://benwinding.com/eat-the-donut.html",
    "tools": [
      "Plain JavaScript"
    ],
    "icons": [
      "javascript",
      "tailwind",
      "three"
    ],
    "thumbnail": "/imgur/projects/_resized/adowubbja213.jpg"
  },
  {
    "slug": "task_barrel",
    "name": "Task Barrel",
    "year": 2021,
    "tags": [
      "productivity",
      "web app"
    ],
    "description": "Simple task collaboration, inspired by 'Github Issues'",
    "deploy_link": "https://taskbarrel.com",
    "tools": [
      "Javascript",
      "React",
      "NextJs",
      "Tailwind"
    ],
    "icons": [
      "react",
      "javascript"
    ],
    "wip": true,
    "thumbnail": "/imgur/projects/_resized/123objkbadwbhad.jpg"
  },
  {
    "slug": "wolfpackdogtrainingcom",
    "name": "WolfpackDogTraining.com",
    "year": 2021,
    "tags": [
      "web site"
    ],
    "description": "Website for a friend's dog training business",
    "deploy_link": "https://wolfpackdogtraining.com",
    "tools": [
      "NextJs",
      "Contentful"
    ],
    "icons": [
      "next",
      "contentful"
    ],
    "thumbnail": "/imgur/projects/_resized/21bekadhcavs.jpg"
  },
  {
    "slug": "zoomore",
    "name": "Zoomore",
    "year": 2021,
    "tags": [
      "fun",
      "mobile app"
    ],
    "description": "Turn pictures into videos",
    "code_link": "https://github.com/benwinding/zoomore",
    "deploy_link": "https://zoomore.benwinding.com/",
    "tools": [
      "Flutter",
      "Android",
      "IOS",
      "Graphics"
    ],
    "icons": [
      "flutter",
      "android",
      "apple"
    ],
    "thumbnail": "/imgur/projects/_resized/qdwajknbkhq2e.jpg"
  },
  {
    "slug": "command_pal",
    "name": "Command Pal",
    "year": 2020,
    "tags": [
      "fun",
      "cli",
      "library"
    ],
    "description": "The hackable command palette for the web, inspired by Visual Studio Code.",
    "code_link": "https://github.com/benwinding/command-pal",
    "deploy_link": "https://benwinding.github.io/command-pal/demos/cp-advanced",
    "article_link": "https://benwinding.github.io/command-pal/docs",
    "tools": [
      "Javascript",
      "Svelte",
      "hotkeys.js",
      "fuse.js"
    ],
    "icons": [
      "svelte"
    ],
    "thumbnail": "/imgur/projects/_resized/adwquig21e.jpg"
  },
  {
    "slug": "ngext",
    "name": "Ngext",
    "year": 2020,
    "tags": [
      "tool",
      "cli",
      "library"
    ],
    "description": "A routing framework for angular inspired by React's next.js.",
    "code_link": "https://github.com/benwinding/ngext",
    "article_link": "https://benwinding.github.io/ngext",
    "tools": [
      "Angular",
      "SSR",
      "NodeJs",
      "File-based routing"
    ],
    "icons": [
      "angular"
    ],
    "thumbnail": "/imgur/projects/_resized/ngexwadubaiuwdb.jpg"
  },
  {
    "slug": "svg_2_clipboard",
    "name": "SVG 2 Clipboard",
    "year": 2020,
    "tags": [
      "extension"
    ],
    "description": "A simple browser extension to help copy SVG's directly from the web!",
    "code_link": "https://github.com/benwinding/svg-2-clipboard",
    "deploy_link": "https://chrome.google.com/webstore/detail/svg-2-clipboard/pacmblooebolmbakblffejfmhmnojece",
    "tools": [
      "JavaScript",
      "SVG",
      "Chrome",
      "Firefox"
    ],
    "icons": [
      "chrome",
      "firefox"
    ],
    "thumbnail": "/imgur/projects/_resized/awdwqawd21.jpg"
  },
  {
    "slug": "wealth_visualizer",
    "name": "Wealth Visualizer",
    "year": 2020,
    "tags": [
      "fun",
      "3d",
      "web app"
    ],
    "description": "A physical visualization of money!",
    "code_link": "https://github.com/benwinding/wealth-visualizer",
    "deploy_link": "https://benwinding.github.io/wealth-visualizer/",
    "tools": [
      "VueJs",
      "Tailwind",
      "Three-Js"
    ],
    "icons": [
      "vue",
      "three"
    ],
    "thumbnail": "/imgur/projects/_resized/12e2kjbadhwabd.jpg"
  },
  {
    "slug": "cloud_html_2_pdf",
    "name": "Cloud HTML 2 PDF",
    "year": 2019,
    "tags": [
      "cloud",
      "library"
    ],
    "description": "Convert HTML to PDF efficiently using google cloud infrastructure",
    "code_link": "https://github.com/benwinding/cloud-html2pdf",
    "tools": [
      "Typescript",
      "PDF",
      "Puppeteer",
      "Google Cloud Run"
    ],
    "icons": [
      "pdf",
      "puppeteer",
      "docker"
    ],
    "thumbnail": "/imgur/projects/_resized/qdwabiub1234.jpg"
  },
  {
    "slug": "frank_the_collie",
    "name": "Frank The Collie",
    "year": 2019,
    "tags": [
      "fun",
      "web site"
    ],
    "description": "A high-performance website for \"Frank\" my Border Collie",
    "code_link": "https://github.com/benwinding/frank-the-collie",
    "deploy_link": "https://benwinding.github.io/frank-the-collie/",
    "tools": [
      "Svelte",
      "Tailwind",
      "Instagram API"
    ],
    "icons": [
      "angular",
      "instagram"
    ],
    "thumbnail": "/imgur/projects/_resized/farawjdbaw.jpg"
  },
  {
    "slug": "canvas_scraper",
    "name": "Canvas Scraper",
    "year": 2018,
    "tags": [
      "fun",
      "library"
    ],
    "description": "Download all files from a specific course on the MyUni system.",
    "code_link": "https://github.com/benwinding/myuni-dl",
    "article_link": "https://blog.benwinding.com/scraping_myuni",
    "tools": [
      "Python",
      "Web Scraping"
    ],
    "icons": [
      "python"
    ],
    "thumbnail": "/imgur/projects/_resized/dwqjn12ejnawdxs.jpg"
  },
  {
    "slug": "down_subs",
    "name": "Down Subs",
    "year": 2018,
    "tags": [
      "fun",
      "web app"
    ],
    "description": "Search videos from youtube, by text in the subtitles",
    "deploy_link": "https://github.com/benwinding/down-subs",
    "tools": [
      "Python",
      "Shell"
    ],
    "icons": [
      "python"
    ],
    "thumbnail": "/imgur/projects/_resized/xalnxjnawjn12.jpg"
  },
  {
    "slug": "my_blog",
    "name": "My Blog",
    "year": 2018,
    "tags": [
      "fun",
      "web site"
    ],
    "description": "Checkout my blog, where I speak my mind",
    "deploy_link": "https://blog.benwinding.com/",
    "tools": [
      "JavaScript",
      "Hexo",
      "Static Site"
    ],
    "icons": [
      "pen"
    ],
    "thumbnail": "/imgur/projects/_resized/axskjn21edxas.jpg"
  },
  {
    "slug": "newsit",
    "name": "Newsit",
    "year": 2018,
    "tags": [
      "hn",
      "extension"
    ],
    "description": "Newsit can find the top voted Reddit or Hacker News discussion!",
    "code_link": "https://github.com/benwinding/newsit",
    "deploy_link": "https://newsit.benwinding.com/",
    "tools": [
      "JavaScript",
      "Bulma",
      "Chrome",
      "Firefox",
      "Hacker News API"
    ],
    "icons": [
      "chrome",
      "firefox",
      "hackernews"
    ],
    "thumbnail": "/imgur/projects/_resized/xalksjnq2edjkqwx.jpg"
  },
  {
    "slug": "ycomments",
    "name": "YComments",
    "year": 2018,
    "tags": [
      "hn",
      "library"
    ],
    "description": "Embedded discussions from Hacker News",
    "code_link": "https://github.com/benwinding/ycomments",
    "deploy_link": "https://ycomments.benwinding.com/",
    "article_link": "https://blog.benwinding.com/why-i-made-ycomments/",
    "tools": [
      "JavaScript",
      "Bulma",
      "Chrome",
      "Firefox"
    ],
    "icons": [
      "hackernews"
    ],
    "thumbnail": "/imgur/projects/_resized/wdoiewdo12ednw.jpg"
  },
  {
    "slug": "benwinding.com",
    "name": "benwinding.com",
    "year": 2018,
    "tags": [
      "fun",
      "web site"
    ],
    "description": "Ben winding's web portal, to show off him and his work!",
    "code_link": "https://github.com/benwinding/benw-portal",
    "deploy_link": "https://benwinding.com",
    "tools": [
      "Vue",
      "nuxt",
      "pts.js",
      "tailwind"
    ],
    "icons": [
      "vue",
      "tailwind"
    ],
    "thumbnail": "/imgur/projects/_resized/i2euh1eb2h1e.jpg"
  },
  {
    "slug": "3d_cricket_lanes",
    "name": "3D Cricket Lanes",
    "year": 2017,
    "tags": [
      "fun",
      "web app",
      "3d"
    ],
    "description": "A 3D demo of a cricket lane system, form Quin's Sport's Nets",
    "deploy_link": "https://benwinding.github.io/CricketNet-Demo/",
    "code_link": "https://github.com/benwinding/CricketNet-Demo",
    "tools": [
      "JavaScript",
      "React",
      "Three-Js"
    ],
    "icons": [
      "react",
      "three"
    ],
    "thumbnail": "/imgur/projects/_resized/jklnadb123e1.jpg"
  },
  {
    "slug": "bsc_shed_maker",
    "name": "BSC Shed Maker",
    "year": 2017,
    "tags": [
      "fun",
      "web app"
    ],
    "description": "A demo 3D shed builder that runs in the browser",
    "deploy_link": "https://benwinding.github.io/BSC-Shed-Configurator/",
    "tools": [
      "JavaScript",
      "AngularJs",
      "Three-Js"
    ],
    "icons": [
      "angular",
      "three"
    ],
    "open_same_page": false,
    "thumbnail": "/imgur/projects/_resized/adlwkawjnd.jpg"
  },
  {
    "slug": "bootleg_wakeboarding_event",
    "name": "Bootleg Wakeboarding Event",
    "year": 2017,
    "tags": [
      "fun",
      "web app",
      "3d"
    ],
    "description": "A 3D demo showcasing wakeboarding obstacles",
    "code_link": "https://github.com/benwinding/angular2-wakepark-teaser",
    "deploy_link": "https://benwinding.github.io/angular2-wakepark-teaser/#/parkPreview",
    "tools": [
      "JavaScript",
      "AngularJs",
      "Three-Js"
    ],
    "icons": [
      "angular",
      "three"
    ],
    "thumbnail": "/imgur/projects/_resized/acklsn23e2qax.jpg"
  },
  {
    "slug": "formzy",
    "name": "Formzy",
    "year": 2017,
    "tags": [
      "fun",
      "web app",
      "pdf"
    ],
    "description": "A automated PDF filler, for the Solar Industry",
    "deploy_link": "https://formzy.herokuapp.com/",
    "tools": [
      "NodeJs",
      "PDFs"
    ],
    "icons": [
      "pdf"
    ],
    "thumbnail": "/imgur/projects/_resized/adwadwbua12312.jpg"
  },
  {
    "slug": "memebot",
    "name": "Memebot",
    "year": 2017,
    "tags": [
      "fun",
      "chatbot"
    ],
    "description": "A messenger bot which finds and sends you memes.",
    "code_link": "https://github.com/benwinding/Meme-Bot-Messenger-Client",
    "deploy_link": "https://memebot.lappr.com.au",
    "tools": [
      "JavaScript",
      "GraphQL",
      "Messenger"
    ],
    "icons": [
      "messenger"
    ],
    "thumbnail": "/imgur/projects/_resized/dwakjbhwad.jpg"
  },
  {
    "slug": "outback_odyssey_site",
    "name": "Outback Odyssey Site",
    "year": 2017,
    "tags": [
      "fun",
      "web site"
    ],
    "description": "An event website for an annual car adventure for charity.",
    "deploy_link": "https://ozoutbackodyssey.com.au",
    "tools": [
      "Wordpress"
    ],
    "icons": [
      "wordpress"
    ],
    "thumbnail": "/imgur/projects/_resized/wdaiuy213wh.jpg"
  },
  {
    "slug": "pdf_stamp",
    "name": "PDF Stamp",
    "year": 2017,
    "tags": [
      "cli",
      "pdf"
    ],
    "description": "Automate adding signatures to a PDF via terminal.",
    "code_link": "https://github.com/benwinding/pdfstamp",
    "tools": [
      "Typescript",
      "PDFkit",
      "ImageMagick"
    ],
    "icons": [
      "typescript",
      "pdf"
    ],
    "thumbnail": "/imgur/projects/_resized/adkmwqad12wqwda.jpg"
  },
  {
    "slug": "seeing_sarawak_site",
    "name": "Seeing Sarawak Site",
    "year": 2017,
    "tags": [
      "fun",
      "web site"
    ],
    "description": "Travel blog, created for my sister",
    "deploy_link": "https://web.archive.org/web/20180826235151/https://seeingsarawak.com/",
    "tools": [
      "Wordpress"
    ],
    "icons": [
      "wordpress"
    ],
    "thumbnail": "/imgur/projects/_resized/adwskj213edqais.jpg"
  },
  {
    "slug": "rachel_darling's_site",
    "name": "Rachel Darling's Site",
    "year": 2016,
    "tags": [
      "fun",
      "web site"
    ],
    "description": "A portfolio website for a talented artist.",
    "deploy_link": "https://rachelkatedarling.com",
    "tools": [
      "Wordpress"
    ],
    "icons": [
      "wordpress"
    ],
    "thumbnail": "/imgur/projects/_resized/dwqlk13290d.jpg"
  },
  {
    "slug": "kova_engineering_site",
    "name": "Kova Engineering Site",
    "year": 2014,
    "tags": [
      "fun",
      "web site"
    ],
    "description": "An engineering firm in Vancouver, Canada.",
    "deploy_link": "https://web.archive.org/web/20150801181953/http://kova.com/",
    "tools": [
      "Wordpress"
    ],
    "icons": [
      "wordpress"
    ],
    "thumbnail": "/imgur/projects/_resized/awdklnj21ejascx.jpg"
  }
];
